name: Release version

env:
  major: 0
  minor: 0

on:
  workflow_dispatch:

jobs:
  deploy-release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: inject secrets
        run: |
          echo MY_SECRET=${{ secrets.MY_SECRET }} >> .env.secrets

      - name: show configs and secrets (debugging) # for debugging, will replace injected values by ***
        run: cat .env*

      - name: run tests
        run: npm run test

      - name: test report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Jest tests
          path: ./reports/jest-test-report.xml
          reporter: jest-junit # format of test results

      - name: build
        run: npm run build

      - name: show file tree (debugging)
        run: ls -alR -I .git -I node_modules -I .vscode -I .github

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        id: changelog_gen
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/**"
          tag: ${{ env.major }}.${{ env.minor }}.${{github.run_id}}
          name: Release ${{ env.major }}.${{ env.minor }}.${{github.run_id}}
          body: ${{ steps.changelog_gen.outputs.changes }}
